@baseUri=http://localhost:3001/api

### test
POST {{baseUri}}/test

### generate wallpaper
POST {{baseUri}}/gen-wallpaper
Content-Type: application/json

{
    "description": "a fat 50yo boy using computer and sitting on wooden floor in the bacolny"
}

### generate wallpaper list
GET {{baseUri}}/gen-wallpapers